### PR TITLE
LAN Region added to proper branch

### PR DESCRIPTION
**Pull request by juaoose**
Spectator IP is still missing.
Not sure if the pull request was properly sent.

### CODE REVIEW

**Comment by eddy5641** [comment]
I can find out the up its okay

**Comment by eddy5641** [comment]
LAS, or LAN?

**Comment by juaoose** [comment]
Only added file is LAN for LA1

**Comment by eddy5641** [comment]
ip is: 66.151.33.19:80

**Comment by juaoose** [comment]
Do you mean the spectator IP for LAN is that one or just that the one LAN.cs file contains is wrong? I got it from support.

**Comment by eddy5641** [comment]
that's the spectator ip

**Comment by juaoose** [comment]
Ok, I'll add that to the pull request as soon as Im on a computer.

**Comment by eddy5641** [comment]
going to merge this to master

**Pull request closed without merging**
