### PR TITLE
replay overview - item mouseover tooltip

### PR DESCRIPTION
**Pull request by horato**
legendaryclient

### CODE REVIEW

**Comment by Dispersia** [comment]
You really seem to like replays :P

**Comment by eddy5641** [comment]
added as collaborator

**Comment by eddy5641** [comment]
been busy with school work, sorry for not commenting anything :(

**Comment by Dispersia** [comment]
It's fine, I've had a lot of projects as well and probably won't do much next week (game design project, yayyyy)

**Pull request merged**
