### PR TITLE
Add LAS Server Region

### PR DESCRIPTION
**Pull request by davedave85**
Dont know how to add a file, so i modify br region for add LAS region.
it have some bugs, chat is not working and also spectate

### CODE REVIEW

**Comment by eddy5641** [comment]
I have started work on LAS Region that doesnt modify BR

**Comment by Unkn0wn-dx** [comment]
You have Skype? So we can talk

**Comment by rftiiv15** [comment]
I'm not Eddy. Lol. You need to talk to eddy. 

-DayLan Carlsted

**Comment by eddy5641** [comment]
My skype ed vo, eddydavinchi
note I do not go on skype alot

**Pull request closed without merging**
