### PR TITLE
Some Commits

### PR DESCRIPTION
**Pull request by RoachxD**
# Tweaks - LCLog
- Removed unused References
- Tweaked the Code
# Added & Changed - ReplayRecorder & DLLS
- Added 'rtmp-sharp.dll' back to the 'DLLS' Folder
- Modified Path of 'ReplayRecorder.csproj' for 'rtml-sharp.dll'
# Modified - LegendaryClient.Patcher
- Changed 'HintPath' for 'MahApps.Metro' as there's a new Stable Release (The old path was for an Alpha Release)
# Little Update - LegendaryClient.Patcher
- Cleaned and tweaked the Code
- Removed unused References
# Clean, clean, clean! - LegendaryClientMLaunch
- Cleaned the code as much as possible
- Removed unused References

### CODE REVIEW

**Comment by horato** [comment]
have you intentionally removed every new line on each file? :D

**Comment by RoachxD** [comment]
I have re-indented the code xD

**Comment by RoachxD** [comment]
Anyways, would you like to give me your SkypeID as I have no one to talk about the Project..?

**Comment by horato** [comment]
I am just a contributor. Send email to Eddy or Dispersia (it can be found on their github) and ask them ;)

**Pull request merged**
